server:
 port: 1111
 
spring:  application:    name: STOCK-PRICE-API
  datasource:    url: jdbc:h2:mem:testDB
    username: SA
    password: null
    driver-class-name: org.h2.Driver  jpa:    hibernate:      ddl-auto: update
      show-sql: true      defer-datasource-initialization: true    generate-ddl: true    database-platform: org.hibernate.dialect.H2Dialect
      
management:  endpoints:    web:      exposure:        include: '*'
        
        
        
        
                      
        